### PR TITLE
delete dir in filestore

### LINKED ISSUE #1266: Space api go delete file function also deletes folder in local storage
### Describe the bug
Space API go exposes a function called DeleteFile(). When I execute this function and in the path param, I pass a path of the folder. This function deletes that folder as well.

### Expected behaviour
It should throw an error that you cannot delete the folder.

### Actual behaviour 
It deletes the folder.

### Your environment
- Space Cloud version: 0.19.2
- OS: ubuntu
- Kubernetes or Docker: direct binary
- The client api version (if applicable): 
- Browser (if applicable): firefox

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

### PR DESCRIPTION
**Pull request by prithvi081099**
Fixes #1266 #1182

### CODE REVIEW

File: gateway/modules/filestore/amazons3/delete.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ func (a *AmazonS3) DeleteFile(ctx context.Context, path string) error {
 func (a *AmazonS3) DeleteDir(ctx context.Context, path string) error {
 	// TODO: Consider AWS operation limit
 	svc := s3.New(a.client)
-
+	path = path[1:]
```
Comment (sharadregoti) [inline gateway/modules/filestore/amazons3/delete.go:29]:
```suggestion
	path = strings.TrimPrefix(path, "/")
```

File: gateway/server/handlers/filestore.go [hunk 2]
```diff
@@ -163,12 +168,21 @@ func HandleDelete(modules *modules.Modules) http.HandlerFunc {
...
-			_ = helpers.Response.SendErrorResponse(ctx, w, status, err.Error())
-			return
+		if fileType == "file" {
+			status, err := fileStore.DeleteFile(ctx, projectID, token, path, v)
+			if err != nil {
+				_ = helpers.Response.SendErrorResponse(ctx, w, status, err.Error())
+				return
+			}
+			_ = helpers.Response.SendResponse(ctx, w, status, map[string]string{})
+		} else if fileType == "folder" {
```
Comment (sharadregoti) [inline gateway/server/handlers/filestore.go:178]:
```suggestion
		} else if fileType == "dir" {
```

**Review by sharadregoti — DISMISSED** [review]

**Comment by sharadregoti** [comment]
The issue #1182 cannot be closed as we need to add DeleteFolder function in go & js client libraries

**Review by YourTechBud — APPROVED** [review]
