### PR TITLE
Ingress Routing request and response when no templates given fix 

### LINKED ISSUE #1078: Ingress routing attempts to unmarshal request and response bodies even when no templates are provided

### PR DESCRIPTION
**Pull request by KavishShah09**
Fixes #1078

### CODE REVIEW

File: gateway/utils/routing/modify.go [hunk 1]
```diff
@@ -32,7 +32,7 @@ func (r *Routing) modifyRequest(ctx context.Context, modules modulesInterface, r
 		}
 
 		if err := json.Unmarshal(data, &params); err != nil {
-			return "", nil, http.StatusBadRequest, utils.LogError("Unable to unmarshal body to JSON", module, handleRequest, err)
+			req.Body = ioutil.NopCloser(bytes.NewBuffer(data))
```
Comment (YourTechBud) [inline gateway/utils/routing/modify.go:35]: Print a warning before this statement

File: gateway/utils/routing/modify.go [hunk 2]
```diff
@@ -82,9 +82,15 @@ func (r *Routing) modifyRequest(ctx context.Context, modules modulesInterface, r
...
+		var data []byte
+		var err error
+		if route.Modify.Tmpl != "" {
+			data, err = ioutil.ReadAll(res.Body)
+			if err != nil {
+				return err
+			}
+		} else {
+			return nil
 		}
```
Comment (YourTechBud) [inline gateway/utils/routing/modify.go:94]: Can we just return nil if `route.Modify.Tmpl == ""`? The code will be much cleaner that way

File: gateway/utils/routing/routes.go [hunk 3]
```diff
@@ -12,8 +12,8 @@ import (
 type routeMapping map[string]config.Routes // The key here is the project name
 
 const (
-	module         string = "ingress-route"
-	handleRequest  string = "handle-request"
+	module string = "ingress-route"
+	// handleRequest  string = "handle-request"
```
Comment (YourTechBud) [inline gateway/utils/routing/routes.go:16]: You'll need this in `utils.LogWarn`
