### PR TITLE
Schema module fixes

### LINKED ISSUE #581: Cannot change field type of indexed field
when changing the Fieldtype, column is drop first and then index is dropped

### LINKED ISSUE #751: Throw error on specifying unknown directives in the db schema
Space Cloud does not throw an error even if we specify an unknown directive in the schema. 

For example, I specified a schema which had `createAt` directive instead of `createdAt` by mistake. I could only find out my mistake while querying the corresponding table. Instead, if space cloud could provide error while schema creation itself, development and debugging time could be saved by the developer

### LINKED ISSUE #828: changing schema throws error
### Describe the bug
when schema created
type users { 
	email: String!     
	id: ID! @primary    
	name: String     
	uid: String!     
}
changing the above schema to show below gives error 
"error":"pq: multiple primary keys for table \"users\" are not allowed"
type users { 
	email: ID! @primary
	name: String     
	uid: String!     
}
### Your environment
- Space Cloud version:v0.17.0
- OS:linux

### LINKED ISSUE #830: changing column name of primary key throws error in schema
### Describe the bug
current schema
type clusters {
  id: ID! @primary
  project_id : String!
  url : String!
}
scheam after changing name of primary key column
type clusters {
  cluster_id: ID! @primary
  project_id : String!
  url : String!
}
throws error
{"error":"pq: column \"cluster_id\" contains null values"}

- Space Cloud version: v0.17.0
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

### LINKED ISSUE #831: removing primary key from schema gives error for postgres
### Describe the bug
current shema
type clusters {
  cluster_id: ID! @primary
  project_id : ID
	user_id : ID!
	type : ID!
  url : String!
}
scheam after removing primary key
type clusters {
  cluster_id: ID!
  project_id : ID
	user_id : ID!
	type : ID!
  url : String!
}
the table is empty
got error
{"error":"pq: constraint \"c_clusters_cluster_id\" of relation \"clusters\" does not exist"}
### Your environment
- Space Cloud version: v0.17.0
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

### PR DESCRIPTION
**Pull request by YourTechBud**
Fixes a few usability bugs in the schema module
- Fixes #581 
- Fixes #751
- Fixes #828 
- Fixes #830 
- Fixes #831

### CODE REVIEW

File: gateway/modules/schema/helpers.go [hunk 1]
```diff
@@ -401,62 +440,49 @@ type indexStruct struct {
...
+			// Set the default sorting scheme if not present
+			if columnInfo.IndexInfo.Sort == "" {
+				columnInfo.IndexInfo.Sort = "asc"
 			}
-			if currentColumnInfo.IsUnique {
-				currentIndexMap[currentColumnInfo.IndexInfo.Group].IsIndexUnique = true
+
+			// Make sure the sort type is either ascending or descending
+			if !(columnInfo.IndexInfo.Sort == "asc" || columnInfo.IndexInfo.Sort == "desc") {
+				return nil, fmt.Errorf("invalid sort type (%s) provided for field (%s)", columnInfo.IndexInfo.Sort, columnInfo.FieldName)
```
Comment (sharadregoti) [inline gateway/modules/schema/helpers.go]: can we do this in the parse function of schema module ?

File: gateway/utils/handlers/graphql.go [hunk 2]
```diff
@@ -29,6 +29,10 @@ func HandleGraphQLRequest(graphql *graphql.Module, syncMan *syncman.Manager) htt
 			return
 		}
 
+		if projectConfig.ContextTime == 0 {
```
Comment (sharadregoti) [inline gateway/utils/handlers/graphql.go]: can we set the default value on creation of project ?

File: gateway/modules/schema/helpers.go [hunk 3]
```diff
@@ -352,17 +365,43 @@ func (c *creationModule) modifyColumn() []string {
...
 
-// modifyColumnType drop the column then creates a new column with provided type
-func (c *creationModule) modifyColumnType(dbType string) []string {
-	queries := []string{}
+func (c *creationModule) removeDirectives() []string {
+	var queries []string
 
 	if c.currentColumnInfo.IsForeign {
 		queries = append(queries, c.removeForeignKey()...)
+		c.currentColumnInfo.IsForeign = false
```
Comment (sharadregoti) [inline gateway/modules/schema/helpers.go]: specify a comment why this is important

File: gateway/modules/schema/helpers.go [hunk 4]
```diff
@@ -128,6 +130,7 @@ func (c *creationModule) addPrimaryKey() string {
 		return ""
 	}
 
+	c.currentColumnInfo.IsPrimary = true
```
Comment (sharadregoti) [inline gateway/modules/schema/helpers.go]: specify why this is important

File: gateway/utils/handlers/graphql.go (hunk 2 above)
Comment (YourTechBud) [reply gateway/utils/handlers/graphql.go]: What if the project already existed? As in space cloud is using config of `v0.16.0`

File: gateway/modules/schema/helpers.go (hunk 1 above)
Comment (YourTechBud) [reply gateway/modules/schema/helpers.go]: I don't know. This was already here. I'll move it somewhere within SetConfig

File: gateway/modules/schema/helpers.go (hunk 3 above)
Comment (YourTechBud) [reply gateway/modules/schema/helpers.go]: We just removed the foreign key. I think its pretty straight forward why i did that. Was to mark foreign key as removed to prevent this from being processed again

File: gateway/modules/schema/helpers.go (hunk 4 above)
Comment (YourTechBud) [reply gateway/modules/schema/helpers.go]: Not needed
