### PR TITLE
Minor bug fixes

### LINKED ISSUE #1100: Check if secrets is the same before initialising the crud module
Currently we only use the connection string and dbname in the crud config to check if the crud block needs to be reinitialised. This will cause a problem when using secrets since the secret value won't be available to the `IsSame` function.

What we need to do is update the conn string value from the secret and pass that to isSame. We also need to store the certificates inside each crud block and check if that is same as well.

**This issue can be solved after merging `0.18.1` in `0.19.0`.**

### PR DESCRIPTION
**Pull request by sharadregoti**
This fixes #1100 #1133 & some minor fixes

### CODE REVIEW

File: gateway/modules/crud/crud.go [hunk 1]
```diff
@@ -148,10 +148,20 @@ func (m *Module) SetConfig(project string, crud config.Crud) error {
 			m.queries[getPreparedQueryKey(strings.TrimPrefix(k, "sql-"), id)] = query
 		}
 
+		// check if connection string starts with secrets
+		secretName, secretKey, isSecretExists := splitConnectionString(v.Conn)
+		if isSecretExists {
+			var err error
+			v.Conn, err = m.getSecrets(project, secretName, secretKey)
```
Comment (YourTechBud) [inline gateway/modules/crud/crud.go:155]: You can't set this here. This will update the config object

File: gateway/modules/filestore/amazons3/read.go [hunk 2]
```diff
@@ -23,14 +25,21 @@ func (a *AmazonS3) ListDir(req *model.ListFilesRequest) ([]*model.ListFilesRespo
...
 	})
+	if err != nil {
+		return nil, err
+	}
 
-	result := []*model.ListFilesResponse{}
+	if len(resp.Contents) == 0 {
+		utils.LogDebug("AWS list response is empty", "amazons3", "list-dir", nil)
+		return nil, nil
+	}
```
Comment (YourTechBud) [inline gateway/modules/filestore/amazons3/read.go:40]: Return an empty array

File: gateway/modules/crud/crud.go [hunk 3]
```diff
@@ -148,10 +148,21 @@ func (m *Module) SetConfig(project string, crud config.Crud) error {
 			m.queries[getPreparedQueryKey(strings.TrimPrefix(k, "sql-"), id)] = query
 		}
 
+		// check if connection string starts with secrets
+		secretName, isSecretExists := splitConnectionString(v.Conn)
+		var connectionString = v.Conn
```
Comment (YourTechBud) [inline gateway/modules/crud/crud.go:153]:
```suggestion
		connectionString := v.Conn
```

File: gateway/managers/syncman/syncman_crud.go [hunk 4]
```diff
@@ -148,17 +148,17 @@ func (s *Manager) GetPreparedQuery(ctx context.Context, project, dbAlias, id str
 			return http.StatusOK, []interface{}{&preparedQueryResponse{ID: id, DBAlias: dbAlias, SQL: preparedQuery.SQL, Arguments: preparedQuery.Arguments, Rule: preparedQuery.Rule}}, nil
 		}
 		preparedQuery := databaseConfig.PreparedQueries
-		var coll []interface{} = make([]interface{}, 0)
+		var coll = make([]interface{}, 0)
```
Comment (YourTechBud) [inline gateway/managers/syncman/syncman_crud.go:151]:
```suggestion
		coll := make([]interface{}, 0)
```

**Comment by YourTechBud** [comment]
Fixes #1022
